export const EXAM_CATEGORIES = [
  "SSC", "Bank", "Railway", "JEE", "NEET", 
  "UPSC", "GATE", "CAT", "NDA", "Board"
];

export const SUB_EXAMS: Record<string, string[]> = {
  SSC: ["SSC CGL", "SSC CHSL", "SSC GD", "SSC MTS", "SSC CPO", "SSC Stenographer"],
  Bank: ["SBI PO", "SBI Clerk", "IBPS PO", "IBPS Clerk", "RRB PO", "RRB Clerk"],
  Railway: ["RRB NTPC", "RRB Group D", "RRB ALP", "RRB JE"],
  JEE: ["JEE Main", "JEE Advanced"],
  NEET: ["NEET UG", "NEET PG"],
  UPSC: ["UPSC CSE Prelims", "UPSC CSE Mains", "UPSC CAPF", "State PSC"],
  GATE: ["GATE CS", "GATE ECE", "GATE ME", "GATE CE", "GATE EE"],
  CAT: ["CAT", "MAT", "XAT"],
  NDA: ["NDA", "CDA", "AFCAT"],
  Board: ["CBSE 10th", "CBSE 12th", "ICSE 10th", "ICSE 12th", "State Board 10th", "State Board 12th"],
};

export const SUBJECTS_BY_EXAM: Record<string, string[]> = {
  "SSC CGL": ["All Subjects", "General Intelligence & Reasoning", "General Awareness", "Quantitative Aptitude", "English Comprehension"],
  "SSC CHSL": ["All Subjects", "General Intelligence & Reasoning", "General Awareness", "Quantitative Aptitude", "English Comprehension"],
  "SSC GD": ["All Subjects", "General Intelligence & Reasoning", "General Knowledge", "Elementary Mathematics", "Hindi/English"],
  "SSC MTS": ["All Subjects", "General Intelligence & Reasoning", "General Knowledge", "Numerical Ability", "English/Hindi"],
  "SSC CPO": ["All Subjects", "General Intelligence & Reasoning", "General Knowledge", "Quantitative Aptitude", "English"],
  "SSC Stenographer": ["All Subjects", "General Intelligence & Reasoning", "General Awareness", "English Language & Comprehension"],
  "SBI PO": ["All Subjects", "Reasoning Ability", "Quantitative Aptitude", "English Language", "General/Financial Awareness"],
  "SBI Clerk": ["All Subjects", "Reasoning Ability", "Quantitative Aptitude", "English Language", "General/Financial Awareness"],
  "IBPS PO": ["All Subjects", "Reasoning Ability", "Quantitative Aptitude", "English Language", "General/Financial Awareness"],
  "IBPS Clerk": ["All Subjects", "Reasoning Ability", "Quantitative Aptitude", "English Language", "General/Financial Awareness"],
  "RRB PO": ["All Subjects", "Reasoning", "Quantitative Aptitude", "English", "General Awareness"],
  "RRB Clerk": ["All Subjects", "Reasoning", "Quantitative Aptitude", "English", "General Awareness"],
  "RRB NTPC": ["All Subjects", "Mathematics", "General Intelligence & Reasoning", "General Awareness"],
  "RRB Group D": ["All Subjects", "Mathematics", "General Intelligence & Reasoning", "General Awareness", "General Science"],
  "RRB ALP": ["All Subjects", "Mathematics", "General Intelligence", "General Science", "Technical Ability"],
  "RRB JE": ["All Subjects", "Mathematics", "General Intelligence", "General Awareness", "General Science"],
  "JEE Main": ["All Subjects", "Physics", "Chemistry", "Mathematics"],
  "JEE Advanced": ["All Subjects", "Physics", "Chemistry", "Mathematics"],
  "NEET UG": ["All Subjects", "Physics", "Chemistry", "Biology (Botany)", "Biology (Zoology)"],
  "NEET PG": ["All Subjects", "Clinical Subjects", "Pre-clinical Subjects", "Para-clinical Subjects"],
  "UPSC CSE Prelims": ["All Subjects", "General Studies Paper 1", "CSAT Paper 2"],
  "UPSC CSE Mains": ["All Subjects", "General Studies 1", "General Studies 2", "General Studies 3", "General Studies 4", "Essay"],
  "UPSC CAPF": ["All Subjects", "General Ability & Intelligence", "General Studies"],
  "State PSC": ["All Subjects", "General Studies", "Reasoning", "Mathematics", "Language"],
  "GATE CS": ["All Subjects", "Data Structures", "Algorithms", "Operating Systems", "DBMS", "Computer Networks", "TOC", "Digital Logic", "Computer Organization"],
  "GATE ECE": ["All Subjects", "Network Theory", "Electronic Devices", "Analog Circuits", "Digital Circuits", "Signals & Systems", "Control Systems", "Communications", "Electromagnetics"],
  "GATE ME": ["All Subjects", "Engineering Mathematics", "Thermodynamics", "Fluid Mechanics", "Manufacturing", "Strength of Materials"],
  "GATE CE": ["All Subjects", "Engineering Mathematics", "Structural Analysis", "Soil Mechanics", "Fluid Mechanics", "Transportation"],
  "GATE EE": ["All Subjects", "Engineering Mathematics", "Electric Circuits", "Electrical Machines", "Power Systems", "Control Systems"],
  "CAT": ["All Subjects", "Verbal Ability & RC", "Data Interpretation & LR", "Quantitative Ability"],
  "MAT": ["All Subjects", "Language Comprehension", "Mathematical Skills", "Data Analysis", "Intelligence & Critical Reasoning"],
  "XAT": ["All Subjects", "Verbal Ability & RC", "Decision Making", "Quantitative Ability & DI"],
  "NDA": ["All Subjects", "Mathematics", "General Ability Test"],
  "CDA": ["All Subjects", "Mathematics", "General Ability Test"],
  "AFCAT": ["All Subjects", "General Awareness", "Verbal Ability", "Numerical Ability", "Reasoning"],
  "CBSE 10th": ["All Subjects", "Mathematics", "Science", "Social Science", "English", "Hindi"],
  "CBSE 12th": ["All Subjects", "Physics", "Chemistry", "Mathematics", "Biology", "English", "Economics", "History", "Geography"],
  "ICSE 10th": ["All Subjects", "Mathematics", "Physics", "Chemistry", "Biology", "English", "History & Civics", "Geography"],
  "ICSE 12th": ["All Subjects", "Physics", "Chemistry", "Mathematics", "Biology", "English", "Economics"],
  "State Board 10th": ["All Subjects", "Mathematics", "Science", "Social Science", "English", "Hindi"],
  "State Board 12th": ["All Subjects", "Physics", "Chemistry", "Mathematics", "Biology", "English"],
};
