/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDoubtSolverRouteImport } from './routes/_authenticated/doubt-solver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMockTestIndexRouteImport } from './routes/_authenticated/mock-test/index'
import { Route as AuthenticatedMockTestTestIdIndexRouteImport } from './routes/_authenticated/mock-test/$testId/index'
import { Route as AuthenticatedMockTestTestIdResultsRouteImport } from './routes/_authenticated/mock-test/$testId/results'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoubtSolverRoute =
  AuthenticatedDoubtSolverRouteImport.update({
    id: '/doubt-solver',
    path: '/doubt-solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMockTestIndexRoute =
  AuthenticatedMockTestIndexRouteImport.update({
    id: '/mock-test/',
    path: '/mock-test/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdIndexRoute =
  AuthenticatedMockTestTestIdIndexRouteImport.update({
    id: '/mock-test/$testId/',
    path: '/mock-test/$testId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdResultsRoute =
  AuthenticatedMockTestTestIdResultsRouteImport.update({
    id: '/mock-test/$testId/results',
    path: '/mock-test/$testId/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/mock-test': typeof AuthenticatedMockTestIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId': typeof AuthenticatedMockTestTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/_authenticated/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/_authenticated/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/_authenticated/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/doubt-solver'
    | '/mock-test/'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/doubt-solver'
    | '/mock-test'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/doubt-solver'
    | '/_authenticated/mock-test/'
    | '/_authenticated/mock-test/$testId/results'
    | '/_authenticated/mock-test/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doubt-solver': {
      id: '/_authenticated/doubt-solver'
      path: '/doubt-solver'
      fullPath: '/doubt-solver'
      preLoaderRoute: typeof AuthenticatedDoubtSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/': {
      id: '/_authenticated/mock-test/'
      path: '/mock-test'
      fullPath: '/mock-test/'
      preLoaderRoute: typeof AuthenticatedMockTestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/': {
      id: '/_authenticated/mock-test/$testId/'
      path: '/mock-test/$testId'
      fullPath: '/mock-test/$testId/'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/results': {
      id: '/_authenticated/mock-test/$testId/results'
      path: '/mock-test/$testId/results'
      fullPath: '/mock-test/$testId/results'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoubtSolverRoute: typeof AuthenticatedDoubtSolverRoute
  AuthenticatedMockTestIndexRoute: typeof AuthenticatedMockTestIndexRoute
  AuthenticatedMockTestTestIdResultsRoute: typeof AuthenticatedMockTestTestIdResultsRoute
  AuthenticatedMockTestTestIdIndexRoute: typeof AuthenticatedMockTestTestIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoubtSolverRoute: AuthenticatedDoubtSolverRoute,
  AuthenticatedMockTestIndexRoute: AuthenticatedMockTestIndexRoute,
  AuthenticatedMockTestTestIdResultsRoute:
    AuthenticatedMockTestTestIdResultsRoute,
  AuthenticatedMockTestTestIdIndexRoute: AuthenticatedMockTestTestIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
