/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDoubtSolverRouteImport } from './routes/_authenticated/doubt-solver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReferralIndexRouteImport } from './routes/_authenticated/referral/index'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner/index'
import { Route as AuthenticatedPerformanceIndexRouteImport } from './routes/_authenticated/performance/index'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedMockTestIndexRouteImport } from './routes/_authenticated/mock-test/index'
import { Route as AuthenticatedCurrentAffairsIndexRouteImport } from './routes/_authenticated/current-affairs/index'
import { Route as AuthenticatedAnalyserIndexRouteImport } from './routes/_authenticated/analyser/index'
import { Route as AuthenticatedMockTestPracticeRouteImport } from './routes/_authenticated/mock-test/practice'
import { Route as AuthenticatedNotesNoteIdIndexRouteImport } from './routes/_authenticated/notes/$noteId/index'
import { Route as AuthenticatedMockTestTestIdIndexRouteImport } from './routes/_authenticated/mock-test/$testId/index'
import { Route as AuthenticatedMockTestTestIdResultsRouteImport } from './routes/_authenticated/mock-test/$testId/results'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoubtSolverRoute =
  AuthenticatedDoubtSolverRouteImport.update({
    id: '/doubt-solver',
    path: '/doubt-solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferralIndexRoute =
  AuthenticatedReferralIndexRouteImport.update({
    id: '/referral/',
    path: '/referral/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerformanceIndexRoute =
  AuthenticatedPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMockTestIndexRoute =
  AuthenticatedMockTestIndexRouteImport.update({
    id: '/mock-test/',
    path: '/mock-test/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCurrentAffairsIndexRoute =
  AuthenticatedCurrentAffairsIndexRouteImport.update({
    id: '/current-affairs/',
    path: '/current-affairs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyserIndexRoute =
  AuthenticatedAnalyserIndexRouteImport.update({
    id: '/analyser/',
    path: '/analyser/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestPracticeRoute =
  AuthenticatedMockTestPracticeRouteImport.update({
    id: '/mock-test/practice',
    path: '/mock-test/practice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesNoteIdIndexRoute =
  AuthenticatedNotesNoteIdIndexRouteImport.update({
    id: '/notes/$noteId/',
    path: '/notes/$noteId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdIndexRoute =
  AuthenticatedMockTestTestIdIndexRouteImport.update({
    id: '/mock-test/$testId/',
    path: '/mock-test/$testId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdResultsRoute =
  AuthenticatedMockTestTestIdResultsRouteImport.update({
    id: '/mock-test/$testId/results',
    path: '/mock-test/$testId/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/analyser/': typeof AuthenticatedAnalyserIndexRoute
  '/current-affairs/': typeof AuthenticatedCurrentAffairsIndexRoute
  '/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/referral/': typeof AuthenticatedReferralIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
  '/notes/$noteId/': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/analyser': typeof AuthenticatedAnalyserIndexRoute
  '/current-affairs': typeof AuthenticatedCurrentAffairsIndexRoute
  '/mock-test': typeof AuthenticatedMockTestIndexRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/performance': typeof AuthenticatedPerformanceIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/referral': typeof AuthenticatedReferralIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId': typeof AuthenticatedMockTestTestIdIndexRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/_authenticated/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/_authenticated/analyser/': typeof AuthenticatedAnalyserIndexRoute
  '/_authenticated/current-affairs/': typeof AuthenticatedCurrentAffairsIndexRoute
  '/_authenticated/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/referral/': typeof AuthenticatedReferralIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/_authenticated/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
  '/_authenticated/notes/$noteId/': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/doubt-solver'
    | '/mock-test/practice'
    | '/analyser/'
    | '/current-affairs/'
    | '/mock-test/'
    | '/notes/'
    | '/performance/'
    | '/planner/'
    | '/referral/'
    | '/settings/'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId/'
    | '/notes/$noteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/doubt-solver'
    | '/mock-test/practice'
    | '/analyser'
    | '/current-affairs'
    | '/mock-test'
    | '/notes'
    | '/performance'
    | '/planner'
    | '/referral'
    | '/settings'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId'
    | '/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/dashboard'
    | '/_authenticated/doubt-solver'
    | '/_authenticated/mock-test/practice'
    | '/_authenticated/analyser/'
    | '/_authenticated/current-affairs/'
    | '/_authenticated/mock-test/'
    | '/_authenticated/notes/'
    | '/_authenticated/performance/'
    | '/_authenticated/planner/'
    | '/_authenticated/referral/'
    | '/_authenticated/settings/'
    | '/_authenticated/mock-test/$testId/results'
    | '/_authenticated/mock-test/$testId/'
    | '/_authenticated/notes/$noteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doubt-solver': {
      id: '/_authenticated/doubt-solver'
      path: '/doubt-solver'
      fullPath: '/doubt-solver'
      preLoaderRoute: typeof AuthenticatedDoubtSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral/': {
      id: '/_authenticated/referral/'
      path: '/referral'
      fullPath: '/referral/'
      preLoaderRoute: typeof AuthenticatedReferralIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance/': {
      id: '/_authenticated/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AuthenticatedPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/': {
      id: '/_authenticated/mock-test/'
      path: '/mock-test'
      fullPath: '/mock-test/'
      preLoaderRoute: typeof AuthenticatedMockTestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/current-affairs/': {
      id: '/_authenticated/current-affairs/'
      path: '/current-affairs'
      fullPath: '/current-affairs/'
      preLoaderRoute: typeof AuthenticatedCurrentAffairsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyser/': {
      id: '/_authenticated/analyser/'
      path: '/analyser'
      fullPath: '/analyser/'
      preLoaderRoute: typeof AuthenticatedAnalyserIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/practice': {
      id: '/_authenticated/mock-test/practice'
      path: '/mock-test/practice'
      fullPath: '/mock-test/practice'
      preLoaderRoute: typeof AuthenticatedMockTestPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$noteId/': {
      id: '/_authenticated/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId/'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/': {
      id: '/_authenticated/mock-test/$testId/'
      path: '/mock-test/$testId'
      fullPath: '/mock-test/$testId/'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/results': {
      id: '/_authenticated/mock-test/$testId/results'
      path: '/mock-test/$testId/results'
      fullPath: '/mock-test/$testId/results'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoubtSolverRoute: typeof AuthenticatedDoubtSolverRoute
  AuthenticatedMockTestPracticeRoute: typeof AuthenticatedMockTestPracticeRoute
  AuthenticatedAnalyserIndexRoute: typeof AuthenticatedAnalyserIndexRoute
  AuthenticatedCurrentAffairsIndexRoute: typeof AuthenticatedCurrentAffairsIndexRoute
  AuthenticatedMockTestIndexRoute: typeof AuthenticatedMockTestIndexRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedPerformanceIndexRoute: typeof AuthenticatedPerformanceIndexRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
  AuthenticatedReferralIndexRoute: typeof AuthenticatedReferralIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedMockTestTestIdResultsRoute: typeof AuthenticatedMockTestTestIdResultsRoute
  AuthenticatedMockTestTestIdIndexRoute: typeof AuthenticatedMockTestTestIdIndexRoute
  AuthenticatedNotesNoteIdIndexRoute: typeof AuthenticatedNotesNoteIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoubtSolverRoute: AuthenticatedDoubtSolverRoute,
  AuthenticatedMockTestPracticeRoute: AuthenticatedMockTestPracticeRoute,
  AuthenticatedAnalyserIndexRoute: AuthenticatedAnalyserIndexRoute,
  AuthenticatedCurrentAffairsIndexRoute: AuthenticatedCurrentAffairsIndexRoute,
  AuthenticatedMockTestIndexRoute: AuthenticatedMockTestIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedPerformanceIndexRoute: AuthenticatedPerformanceIndexRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
  AuthenticatedReferralIndexRoute: AuthenticatedReferralIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedMockTestTestIdResultsRoute:
    AuthenticatedMockTestTestIdResultsRoute,
  AuthenticatedMockTestTestIdIndexRoute: AuthenticatedMockTestTestIdIndexRoute,
  AuthenticatedNotesNoteIdIndexRoute: AuthenticatedNotesNoteIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
