/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDoubtSolverRouteImport } from './routes/_authenticated/doubt-solver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedVaultIndexRouteImport } from './routes/_authenticated/vault/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRevisionPacksIndexRouteImport } from './routes/_authenticated/revision-packs/index'
import { Route as AuthenticatedReferralIndexRouteImport } from './routes/_authenticated/referral/index'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner/index'
import { Route as AuthenticatedPerformanceIndexRouteImport } from './routes/_authenticated/performance/index'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedMockTestIndexRouteImport } from './routes/_authenticated/mock-test/index'
import { Route as AuthenticatedMistakesIndexRouteImport } from './routes/_authenticated/mistakes/index'
import { Route as AuthenticatedCurrentAffairsIndexRouteImport } from './routes/_authenticated/current-affairs/index'
import { Route as AuthenticatedAnalyserIndexRouteImport } from './routes/_authenticated/analyser/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedRevisionPacksPackIdRouteImport } from './routes/_authenticated/revision-packs/$packId'
import { Route as AuthenticatedMockTestPracticeRouteImport } from './routes/_authenticated/mock-test/practice'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedNotesNoteIdIndexRouteImport } from './routes/_authenticated/notes/$noteId/index'
import { Route as AuthenticatedMockTestTestIdIndexRouteImport } from './routes/_authenticated/mock-test/$testId/index'
import { Route as AuthenticatedMockTestTestIdResultsRouteImport } from './routes/_authenticated/mock-test/$testId/results'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoubtSolverRoute =
  AuthenticatedDoubtSolverRouteImport.update({
    id: '/doubt-solver',
    path: '/doubt-solver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultIndexRoute = AuthenticatedVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevisionPacksIndexRoute =
  AuthenticatedRevisionPacksIndexRouteImport.update({
    id: '/revision-packs/',
    path: '/revision-packs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferralIndexRoute =
  AuthenticatedReferralIndexRouteImport.update({
    id: '/referral/',
    path: '/referral/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerformanceIndexRoute =
  AuthenticatedPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMockTestIndexRoute =
  AuthenticatedMockTestIndexRouteImport.update({
    id: '/mock-test/',
    path: '/mock-test/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMistakesIndexRoute =
  AuthenticatedMistakesIndexRouteImport.update({
    id: '/mistakes/',
    path: '/mistakes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCurrentAffairsIndexRoute =
  AuthenticatedCurrentAffairsIndexRouteImport.update({
    id: '/current-affairs/',
    path: '/current-affairs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyserIndexRoute =
  AuthenticatedAnalyserIndexRouteImport.update({
    id: '/analyser/',
    path: '/analyser/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedRevisionPacksPackIdRoute =
  AuthenticatedRevisionPacksPackIdRouteImport.update({
    id: '/revision-packs/$packId',
    path: '/revision-packs/$packId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestPracticeRoute =
  AuthenticatedMockTestPracticeRouteImport.update({
    id: '/mock-test/practice',
    path: '/mock-test/practice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedNotesNoteIdIndexRoute =
  AuthenticatedNotesNoteIdIndexRouteImport.update({
    id: '/notes/$noteId/',
    path: '/notes/$noteId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdIndexRoute =
  AuthenticatedMockTestTestIdIndexRouteImport.update({
    id: '/mock-test/$testId/',
    path: '/mock-test/$testId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestTestIdResultsRoute =
  AuthenticatedMockTestTestIdResultsRouteImport.update({
    id: '/mock-test/$testId/results',
    path: '/mock-test/$testId/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/revision-packs/$packId': typeof AuthenticatedRevisionPacksPackIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/analyser/': typeof AuthenticatedAnalyserIndexRoute
  '/current-affairs/': typeof AuthenticatedCurrentAffairsIndexRoute
  '/mistakes/': typeof AuthenticatedMistakesIndexRoute
  '/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/referral/': typeof AuthenticatedReferralIndexRoute
  '/revision-packs/': typeof AuthenticatedRevisionPacksIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/vault/': typeof AuthenticatedVaultIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
  '/notes/$noteId/': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/revision-packs/$packId': typeof AuthenticatedRevisionPacksPackIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/analyser': typeof AuthenticatedAnalyserIndexRoute
  '/current-affairs': typeof AuthenticatedCurrentAffairsIndexRoute
  '/mistakes': typeof AuthenticatedMistakesIndexRoute
  '/mock-test': typeof AuthenticatedMockTestIndexRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/performance': typeof AuthenticatedPerformanceIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/referral': typeof AuthenticatedReferralIndexRoute
  '/revision-packs': typeof AuthenticatedRevisionPacksIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/vault': typeof AuthenticatedVaultIndexRoute
  '/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/mock-test/$testId': typeof AuthenticatedMockTestTestIdIndexRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doubt-solver': typeof AuthenticatedDoubtSolverRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/mock-test/practice': typeof AuthenticatedMockTestPracticeRoute
  '/_authenticated/revision-packs/$packId': typeof AuthenticatedRevisionPacksPackIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/analyser/': typeof AuthenticatedAnalyserIndexRoute
  '/_authenticated/current-affairs/': typeof AuthenticatedCurrentAffairsIndexRoute
  '/_authenticated/mistakes/': typeof AuthenticatedMistakesIndexRoute
  '/_authenticated/mock-test/': typeof AuthenticatedMockTestIndexRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/referral/': typeof AuthenticatedReferralIndexRoute
  '/_authenticated/revision-packs/': typeof AuthenticatedRevisionPacksIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/vault/': typeof AuthenticatedVaultIndexRoute
  '/_authenticated/mock-test/$testId/results': typeof AuthenticatedMockTestTestIdResultsRoute
  '/_authenticated/mock-test/$testId/': typeof AuthenticatedMockTestTestIdIndexRoute
  '/_authenticated/notes/$noteId/': typeof AuthenticatedNotesNoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/doubt-solver'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/media'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/users'
    | '/mock-test/practice'
    | '/revision-packs/$packId'
    | '/admin/'
    | '/analyser/'
    | '/current-affairs/'
    | '/mistakes/'
    | '/mock-test/'
    | '/notes/'
    | '/performance/'
    | '/planner/'
    | '/referral/'
    | '/revision-packs/'
    | '/settings/'
    | '/vault/'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId/'
    | '/notes/$noteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/doubt-solver'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/media'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/users'
    | '/mock-test/practice'
    | '/revision-packs/$packId'
    | '/admin'
    | '/analyser'
    | '/current-affairs'
    | '/mistakes'
    | '/mock-test'
    | '/notes'
    | '/performance'
    | '/planner'
    | '/referral'
    | '/revision-packs'
    | '/settings'
    | '/vault'
    | '/mock-test/$testId/results'
    | '/mock-test/$testId'
    | '/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/doubt-solver'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/mock-test/practice'
    | '/_authenticated/revision-packs/$packId'
    | '/_authenticated/admin/'
    | '/_authenticated/analyser/'
    | '/_authenticated/current-affairs/'
    | '/_authenticated/mistakes/'
    | '/_authenticated/mock-test/'
    | '/_authenticated/notes/'
    | '/_authenticated/performance/'
    | '/_authenticated/planner/'
    | '/_authenticated/referral/'
    | '/_authenticated/revision-packs/'
    | '/_authenticated/settings/'
    | '/_authenticated/vault/'
    | '/_authenticated/mock-test/$testId/results'
    | '/_authenticated/mock-test/$testId/'
    | '/_authenticated/notes/$noteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doubt-solver': {
      id: '/_authenticated/doubt-solver'
      path: '/doubt-solver'
      fullPath: '/doubt-solver'
      preLoaderRoute: typeof AuthenticatedDoubtSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vault/': {
      id: '/_authenticated/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AuthenticatedVaultIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revision-packs/': {
      id: '/_authenticated/revision-packs/'
      path: '/revision-packs'
      fullPath: '/revision-packs/'
      preLoaderRoute: typeof AuthenticatedRevisionPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral/': {
      id: '/_authenticated/referral/'
      path: '/referral'
      fullPath: '/referral/'
      preLoaderRoute: typeof AuthenticatedReferralIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance/': {
      id: '/_authenticated/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AuthenticatedPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/': {
      id: '/_authenticated/mock-test/'
      path: '/mock-test'
      fullPath: '/mock-test/'
      preLoaderRoute: typeof AuthenticatedMockTestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mistakes/': {
      id: '/_authenticated/mistakes/'
      path: '/mistakes'
      fullPath: '/mistakes/'
      preLoaderRoute: typeof AuthenticatedMistakesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/current-affairs/': {
      id: '/_authenticated/current-affairs/'
      path: '/current-affairs'
      fullPath: '/current-affairs/'
      preLoaderRoute: typeof AuthenticatedCurrentAffairsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyser/': {
      id: '/_authenticated/analyser/'
      path: '/analyser'
      fullPath: '/analyser/'
      preLoaderRoute: typeof AuthenticatedAnalyserIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/revision-packs/$packId': {
      id: '/_authenticated/revision-packs/$packId'
      path: '/revision-packs/$packId'
      fullPath: '/revision-packs/$packId'
      preLoaderRoute: typeof AuthenticatedRevisionPacksPackIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/practice': {
      id: '/_authenticated/mock-test/practice'
      path: '/mock-test/practice'
      fullPath: '/mock-test/practice'
      preLoaderRoute: typeof AuthenticatedMockTestPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/notes/$noteId/': {
      id: '/_authenticated/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId/'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/': {
      id: '/_authenticated/mock-test/$testId/'
      path: '/mock-test/$testId'
      fullPath: '/mock-test/$testId/'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test/$testId/results': {
      id: '/_authenticated/mock-test/$testId/results'
      path: '/mock-test/$testId/results'
      fullPath: '/mock-test/$testId/results'
      preLoaderRoute: typeof AuthenticatedMockTestTestIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoubtSolverRoute: typeof AuthenticatedDoubtSolverRoute
  AuthenticatedMockTestPracticeRoute: typeof AuthenticatedMockTestPracticeRoute
  AuthenticatedRevisionPacksPackIdRoute: typeof AuthenticatedRevisionPacksPackIdRoute
  AuthenticatedAnalyserIndexRoute: typeof AuthenticatedAnalyserIndexRoute
  AuthenticatedCurrentAffairsIndexRoute: typeof AuthenticatedCurrentAffairsIndexRoute
  AuthenticatedMistakesIndexRoute: typeof AuthenticatedMistakesIndexRoute
  AuthenticatedMockTestIndexRoute: typeof AuthenticatedMockTestIndexRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedPerformanceIndexRoute: typeof AuthenticatedPerformanceIndexRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
  AuthenticatedReferralIndexRoute: typeof AuthenticatedReferralIndexRoute
  AuthenticatedRevisionPacksIndexRoute: typeof AuthenticatedRevisionPacksIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedVaultIndexRoute: typeof AuthenticatedVaultIndexRoute
  AuthenticatedMockTestTestIdResultsRoute: typeof AuthenticatedMockTestTestIdResultsRoute
  AuthenticatedMockTestTestIdIndexRoute: typeof AuthenticatedMockTestTestIdIndexRoute
  AuthenticatedNotesNoteIdIndexRoute: typeof AuthenticatedNotesNoteIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoubtSolverRoute: AuthenticatedDoubtSolverRoute,
  AuthenticatedMockTestPracticeRoute: AuthenticatedMockTestPracticeRoute,
  AuthenticatedRevisionPacksPackIdRoute: AuthenticatedRevisionPacksPackIdRoute,
  AuthenticatedAnalyserIndexRoute: AuthenticatedAnalyserIndexRoute,
  AuthenticatedCurrentAffairsIndexRoute: AuthenticatedCurrentAffairsIndexRoute,
  AuthenticatedMistakesIndexRoute: AuthenticatedMistakesIndexRoute,
  AuthenticatedMockTestIndexRoute: AuthenticatedMockTestIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedPerformanceIndexRoute: AuthenticatedPerformanceIndexRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
  AuthenticatedReferralIndexRoute: AuthenticatedReferralIndexRoute,
  AuthenticatedRevisionPacksIndexRoute: AuthenticatedRevisionPacksIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedVaultIndexRoute: AuthenticatedVaultIndexRoute,
  AuthenticatedMockTestTestIdResultsRoute:
    AuthenticatedMockTestTestIdResultsRoute,
  AuthenticatedMockTestTestIdIndexRoute: AuthenticatedMockTestTestIdIndexRoute,
  AuthenticatedNotesNoteIdIndexRoute: AuthenticatedNotesNoteIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
