-- 1. question_bank table
create table if not exists public.question_bank (
  id uuid primary key default gen_random_uuid(),
  exam text not null,
  sub_exam text not null,
  subject text not null,
  topic text,
  difficulty text not null default 'medium',
  language text not null default 'en',
  question text not null,
  options jsonb not null,
  correct_index int not null check (correct_index between 0 and 3),
  explanation text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_question_bank_filter
  on public.question_bank (sub_exam, subject, difficulty, language);

alter table public.question_bank enable row level security;

create policy "Authenticated can read question bank"
  on public.question_bank for select
  to authenticated
  using (true);

-- 2. daily_usage.ai_tests_used
alter table public.daily_usage
  add column if not exists ai_tests_used int not null default 0;

-- 3. Seed 50 SSC CGL General Awareness questions
insert into public.question_bank (exam, sub_exam, subject, topic, difficulty, language, question, options, correct_index, explanation) values
('SSC','SSC CGL','General Awareness','History','easy','en','Who was the first Governor-General of independent India?',
  '["Lord Mountbatten","C. Rajagopalachari","Jawaharlal Nehru","Rajendra Prasad"]'::jsonb,0,'Lord Mountbatten served as the first Governor-General of independent India from August 1947 to June 1948.'),
('SSC','SSC CGL','General Awareness','Polity','easy','en','How many fundamental rights are guaranteed by the Indian Constitution?',
  '["5","6","7","8"]'::jsonb,1,'After the 44th Amendment removed the Right to Property, six fundamental rights remain.'),
('SSC','SSC CGL','General Awareness','Geography','easy','en','Which is the longest river in India?',
  '["Yamuna","Ganga","Godavari","Brahmaputra"]'::jsonb,1,'The Ganga is the longest river flowing entirely within India at about 2,525 km.'),
('SSC','SSC CGL','General Awareness','Science','easy','en','What is the chemical symbol for gold?',
  '["Go","Gd","Au","Ag"]'::jsonb,2,'The symbol Au comes from the Latin word "aurum" meaning gold.'),
('SSC','SSC CGL','General Awareness','Economy','medium','en','The Reserve Bank of India was nationalised in which year?',
  '["1935","1947","1949","1969"]'::jsonb,2,'RBI was nationalised on 1 January 1949 under the Reserve Bank (Transfer to Public Ownership) Act, 1948.'),
('SSC','SSC CGL','General Awareness','History','medium','en','The Battle of Plassey was fought in which year?',
  '["1757","1764","1857","1764"]'::jsonb,0,'The Battle of Plassey was fought on 23 June 1757 between the British East India Company and Siraj-ud-Daulah.'),
('SSC','SSC CGL','General Awareness','Polity','medium','en','Who is known as the Father of the Indian Constitution?',
  '["Mahatma Gandhi","B. R. Ambedkar","Sardar Patel","Rajendra Prasad"]'::jsonb,1,'Dr. B. R. Ambedkar chaired the Drafting Committee of the Constituent Assembly.'),
('SSC','SSC CGL','General Awareness','Geography','medium','en','Which mountain range separates India from China?',
  '["Aravalli","Vindhya","Himalayas","Western Ghats"]'::jsonb,2,'The Himalayan range forms the natural northern border between India and China.'),
('SSC','SSC CGL','General Awareness','Science','easy','en','What is the SI unit of electric current?',
  '["Volt","Ampere","Ohm","Watt"]'::jsonb,1,'The Ampere (A) is the SI base unit of electric current.'),
('SSC','SSC CGL','General Awareness','Science','easy','en','Photosynthesis primarily occurs in which part of the plant?',
  '["Roots","Stem","Leaves","Flowers"]'::jsonb,2,'Chloroplasts in leaves carry out most of the photosynthesis.'),
('SSC','SSC CGL','General Awareness','History','easy','en','Who founded the Mauryan Empire?',
  '["Ashoka","Chandragupta Maurya","Bindusara","Bimbisara"]'::jsonb,1,'Chandragupta Maurya founded the Mauryan Empire around 322 BCE.'),
('SSC','SSC CGL','General Awareness','Polity','easy','en','The President of India is elected by',
  '["Direct vote of citizens","Parliament only","Electoral College","Prime Minister"]'::jsonb,2,'The Electoral College consisting of elected members of both Houses of Parliament and State Assemblies elects the President.'),
('SSC','SSC CGL','General Awareness','Economy','medium','en','GST was implemented in India in which year?',
  '["2015","2016","2017","2018"]'::jsonb,2,'Goods and Services Tax (GST) was rolled out on 1 July 2017.'),
('SSC','SSC CGL','General Awareness','Geography','easy','en','The Tropic of Cancer passes through how many Indian states?',
  '["6","7","8","9"]'::jsonb,2,'It passes through 8 Indian states from Gujarat to Mizoram.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','Which gas is most abundant in the Earth''s atmosphere?',
  '["Oxygen","Nitrogen","Carbon dioxide","Argon"]'::jsonb,1,'Nitrogen makes up about 78% of the Earth''s atmosphere.'),
('SSC','SSC CGL','General Awareness','History','medium','en','The Quit India Movement was launched in',
  '["1940","1942","1945","1947"]'::jsonb,1,'Mahatma Gandhi launched the Quit India Movement on 8 August 1942.'),
('SSC','SSC CGL','General Awareness','Polity','medium','en','How many schedules are there in the Indian Constitution?',
  '["10","11","12","13"]'::jsonb,2,'The Constitution currently has 12 schedules.'),
('SSC','SSC CGL','General Awareness','Geography','medium','en','Which is the largest state of India by area?',
  '["Madhya Pradesh","Maharashtra","Rajasthan","Uttar Pradesh"]'::jsonb,2,'Rajasthan is the largest Indian state by area at 342,239 km².'),
('SSC','SSC CGL','General Awareness','Science','easy','en','Which vitamin is produced by the human body in sunlight?',
  '["Vitamin A","Vitamin B","Vitamin C","Vitamin D"]'::jsonb,3,'Skin produces Vitamin D when exposed to UV-B sunlight.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','The pH value of pure water is',
  '["0","7","10","14"]'::jsonb,1,'Pure water is neutral with a pH of 7.'),
('SSC','SSC CGL','General Awareness','Sports','easy','en','How many players are there in a cricket team?',
  '["9","10","11","12"]'::jsonb,2,'A cricket team has 11 players on the field.'),
('SSC','SSC CGL','General Awareness','Sports','easy','en','The FIFA World Cup is held every',
  '["2 years","3 years","4 years","5 years"]'::jsonb,2,'The FIFA World Cup is held every four years.'),
('SSC','SSC CGL','General Awareness','Awards','medium','en','The Bharat Ratna is India''s',
  '["Highest civilian award","Highest military award","Highest sports award","Highest literary award"]'::jsonb,0,'The Bharat Ratna is the highest civilian award of the Republic of India.'),
('SSC','SSC CGL','General Awareness','History','hard','en','Who was the founder of the Slave Dynasty?',
  '["Iltutmish","Qutb-ud-din Aibak","Razia Sultan","Balban"]'::jsonb,1,'Qutb-ud-din Aibak founded the Slave (Mamluk) Dynasty in 1206.'),
('SSC','SSC CGL','General Awareness','Polity','hard','en','Which Article of the Indian Constitution deals with the abolition of untouchability?',
  '["Article 14","Article 15","Article 17","Article 21"]'::jsonb,2,'Article 17 abolishes untouchability and forbids its practice in any form.'),
('SSC','SSC CGL','General Awareness','Geography','medium','en','The Sundarbans delta is formed by which rivers?',
  '["Ganga and Yamuna","Ganga and Brahmaputra","Krishna and Godavari","Narmada and Tapi"]'::jsonb,1,'The Sundarbans delta is formed at the confluence of the Ganga and Brahmaputra rivers.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','Which organ in the human body produces insulin?',
  '["Liver","Kidney","Pancreas","Stomach"]'::jsonb,2,'The beta cells of the pancreas produce insulin.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','What is the speed of light in vacuum (approx)?',
  '["3 × 10^5 km/s","3 × 10^8 m/s","3 × 10^6 m/s","3 × 10^10 m/s"]'::jsonb,1,'Light travels in vacuum at approximately 3 × 10⁸ metres per second.'),
('SSC','SSC CGL','General Awareness','History','easy','en','The Indian National Congress was founded in',
  '["1875","1885","1905","1915"]'::jsonb,1,'A. O. Hume founded the Indian National Congress in 1885.'),
('SSC','SSC CGL','General Awareness','History','medium','en','Who gave the slogan "Inquilab Zindabad"?',
  '["Bhagat Singh","Subhas Chandra Bose","Chandrashekhar Azad","Bal Gangadhar Tilak"]'::jsonb,0,'Bhagat Singh popularised the slogan "Inquilab Zindabad" (Long Live the Revolution).'),
('SSC','SSC CGL','General Awareness','Polity','easy','en','The minimum age to become President of India is',
  '["25","30","35","40"]'::jsonb,2,'Article 58 requires the President to be at least 35 years old.'),
('SSC','SSC CGL','General Awareness','Polity','medium','en','Money bills can be introduced only in',
  '["Rajya Sabha","Lok Sabha","Either House","Joint sitting"]'::jsonb,1,'Article 110 mandates money bills be introduced only in the Lok Sabha.'),
('SSC','SSC CGL','General Awareness','Economy','medium','en','Which is the central bank of India?',
  '["State Bank of India","Reserve Bank of India","ICICI Bank","Axis Bank"]'::jsonb,1,'The Reserve Bank of India is the central banking institution.'),
('SSC','SSC CGL','General Awareness','Economy','hard','en','Repo rate in India is decided by',
  '["Government of India","RBI Monetary Policy Committee","Finance Ministry","SEBI"]'::jsonb,1,'The Monetary Policy Committee of the RBI sets the repo rate.'),
('SSC','SSC CGL','General Awareness','Geography','easy','en','Which is the smallest continent by area?',
  '["Europe","Antarctica","Australia","South America"]'::jsonb,2,'Australia is the smallest continent at about 8.6 million km².'),
('SSC','SSC CGL','General Awareness','Geography','medium','en','The Konkan coast lies between',
  '["Goa and Cochin","Mumbai and Goa","Mumbai and Mangalore","Surat and Mumbai"]'::jsonb,1,'The Konkan coast is the western coastline stretching roughly from Mumbai to Goa.'),
('SSC','SSC CGL','General Awareness','Science','easy','en','How many bones are there in the adult human body?',
  '["196","206","216","226"]'::jsonb,1,'An adult human body has 206 bones.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','Which planet is known as the Red Planet?',
  '["Venus","Mars","Jupiter","Saturn"]'::jsonb,1,'Mars appears reddish due to iron oxide on its surface.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','The hardest natural substance on Earth is',
  '["Gold","Iron","Diamond","Platinum"]'::jsonb,2,'Diamond is the hardest known naturally occurring material.'),
('SSC','SSC CGL','General Awareness','Sports','medium','en','The Davis Cup is associated with',
  '["Cricket","Football","Tennis","Hockey"]'::jsonb,2,'The Davis Cup is the premier international team event in men''s tennis.'),
('SSC','SSC CGL','General Awareness','Sports','easy','en','Where will the 2028 Summer Olympics be held?',
  '["Paris","Los Angeles","Brisbane","Tokyo"]'::jsonb,1,'Los Angeles will host the 2028 Summer Olympics.'),
('SSC','SSC CGL','General Awareness','Awards','medium','en','The Nobel Prize is awarded in how many categories?',
  '["4","5","6","7"]'::jsonb,2,'Six categories: Physics, Chemistry, Medicine, Literature, Peace, and Economic Sciences.'),
('SSC','SSC CGL','General Awareness','History','medium','en','The Dandi March was led by Mahatma Gandhi in',
  '["1920","1928","1930","1942"]'::jsonb,2,'The Dandi March (Salt Satyagraha) began on 12 March 1930.'),
('SSC','SSC CGL','General Awareness','History','easy','en','Who was the last Mughal emperor?',
  '["Akbar II","Bahadur Shah II","Shah Alam II","Aurangzeb"]'::jsonb,1,'Bahadur Shah Zafar (II) was the last Mughal emperor, exiled in 1858.'),
('SSC','SSC CGL','General Awareness','Polity','hard','en','The 73rd Constitutional Amendment Act deals with',
  '["GST","Panchayati Raj","Education","Anti-defection"]'::jsonb,1,'The 73rd Amendment (1992) gave constitutional status to Panchayati Raj institutions.'),
('SSC','SSC CGL','General Awareness','Geography','medium','en','Which is the highest waterfall in India?',
  '["Jog Falls","Kunchikal Falls","Dudhsagar Falls","Hogenakkal Falls"]'::jsonb,1,'Kunchikal Falls in Karnataka is India''s tallest at about 455 m.'),
('SSC','SSC CGL','General Awareness','Science','easy','en','Which blood group is the universal donor?',
  '["A","B","O negative","AB"]'::jsonb,2,'O-negative red cells can be transfused to almost any recipient.'),
('SSC','SSC CGL','General Awareness','Science','medium','en','The deficiency of which vitamin causes scurvy?',
  '["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"]'::jsonb,2,'Scurvy is caused by a prolonged deficiency of vitamin C.'),
('SSC','SSC CGL','General Awareness','Awards','medium','en','The Booker Prize is awarded for excellence in',
  '["Science","Literature","Music","Cinema"]'::jsonb,1,'The Booker Prize is awarded for the best novel written in English.'),
('SSC','SSC CGL','General Awareness','Polity','medium','en','The Right to Education was made a fundamental right by which amendment?',
  '["86th","73rd","74th","91st"]'::jsonb,0,'The 86th Amendment (2002) inserted Article 21A making free and compulsory education for children aged 6–14 a fundamental right.');
